---
- name: Get info
  gather_facts: true
  hosts: all
  tasks:
    - name: Include all default extension files in vars
      include_vars:
        dir: vars

    - name: setup
      setup:

    - name: OS check
      fail:
        msg: "Wrong OS '{{ hostvars[inventory_hostname].ansible_distribution }} {{ hostvars[inventory_hostname].ansible_distribution_version }}'."
      when:
        hostvars[inventory_hostname].ansible_distribution != "Ubuntu" or
        hostvars[inventory_hostname].ansible_distribution_version != "18.04"

    - name: mkdir out
      local_action: file path="out" state=directory

    - name: dump
      local_action: copy content="{{ hostvars }}" dest=out/facts.json
