---
- name: Create libvirt stuff
  gather_facts: true
  hosts: all
  tasks:
    - name: Include all default extension files in vars
      include_vars:
        dir: vars

    - name: setup
      setup:

    - name: install kvm
      apt: pkg=qemu-kvm,libvirt-bin,virtinst,virt-top,bridge-utils,qemu,python-lxml state=present

    - name: ensure libvirt-bin is started
      service: name=libvirt-bin state=started enabled=true

    - include_tasks: net.yaml
      with_items: "{{ virt_networks }}"

